version: 2

jobs:
  build:
    docker:
      - image: jochym/indi-docker:bionic
    branch:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Build all
          command: .circleci/build-all.sh
      - run:
          name: Run tests
          command: .circleci/run-tests.sh
 
